import { chromium } from 'playwright';
const dir='/tmp/claude-0/-home-user-salesarena-matcher/72f947a2-1995-592e-9f8e-35d42426fd74/scratchpad';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 860, height: 640 } });
const errs=[]; p.on('pageerror', e=>errs.push(e.message));
await p.goto(process.argv[2], { waitUntil: 'networkidle' });
await p.waitForTimeout(400);
await p.evaluate(()=>document.documentElement.classList.add('dark'));
await p.waitForTimeout(250);
await p.screenshot({ path: `${dir}/${process.argv[3]}-dark.png`, fullPage: true });
await p.evaluate(()=>document.documentElement.classList.remove('dark'));
await p.waitForTimeout(250);
await p.screenshot({ path: `${dir}/${process.argv[3]}-light.png`, fullPage: true });
console.log('errores:', errs.length ? errs : 'ninguno');
await b.close();
